version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: gateway_MBCtest_DB
    ports:
      - "27017:27017"
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=sanh
      # - MONGO_INITDB_ROOT_PASSWORD=changeme
      - MONGO_INITDB_DATABASE=Shoping_Management
      # - MONGODB_URL=mongodb://127.0.0.1:27017
    # restart: always
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
