version: '3.3'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo-docker
    environment:
      # MONGO_INITDB_ROOT_USERNAME: mongo
      # MONGO_INITDB_ROOT_PASSWORD: changeme
      MONGO_INITDB_DATABASE: mongo
      # MONGODB_URL: mongodb://mongo:changeme@127.0.0.1:27017/mongo

      # MONGODB_AUTH_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - ./workspace:/workspace
      - type: volume
        source: mongodb_data_volume
        target: /data/db
    # environment:
    #   # - MONGO_INITDB_ROOT_USERNAME=sanh
    #   # - MONGO_INITDB_ROOT_PASSWORD=changeme
    #   - MONGO_INITDB_DATABASE=Shoping_Management
    #   # - MONGODB_URL=mongodb://127.0.0.1:27017
    # # restart: always
    # volumes:
    #   - dbdata6:/data/db
        
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin

      # ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      # ME_CONFIG_MONGODB_URL: mongo://mongoadmin:mongoadmin@mongo:27017/ 
    depends_on:
      - mongo

volumes:
  mongodb_data_volume:
    driver: local    
    